"""Add title col to Note

Revision ID: 12a3a8f8d28b
Revises: 76ece36792dd
Create Date: 2022-11-10 19:58:23.758941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a3a8f8d28b'
down_revision = '76ece36792dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
